### ISSUE TITLE
Can't Install due to Missing Pip Version

### ISSUE THREAD

**Issue by sneilan** [data-describe/data-describe#362]
I tried installing data_describe on python 3.6.9. It seems like your package is either not published to pip or is missing something.

```
(venv) ➜  art pip install data_describe
Collecting data_describe
  Could not find a version that satisfies the requirement data_describe (from versions: )
No matching distribution found for data_describe
(venv) ➜  art python
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by haishiro** [comment]
data-describe currently requires Python 3.7+. 

We started with 3.7 using a soft rule of 2 year backward compatibility, but we can investigate how far back we can support Python versions without introducing significant complexity.

**Comment by sneilan** [comment]
Actually, instead of testing all python versions, why not update the installation requirements?

I can even save you the time and make a PR for this.

**Comment by haishiro** [comment]
PRs are certainly welcome! Not sure if I'm understanding correctly, but #365 is about expanding our CI testing to actually test on all supported version of Python, when we only test on 3.7 currently.

Re: the original issue: I'm also checking older Python versions and it looks like 3.6 is the furthest back we can go due to usage of f-strings and variable type hints. Will need to do some additional checks to be completely sure but I think we can probably go ahead and update setup.py + PyPI to reflect this.

**Comment by sneilan** [comment]
Thank you so much for looking into that! I'll keep an eye out for things I can improve.
